extends: default

rules:
  document-start: disable
  line-length:
    max: 140
    allow-non-breakable-inline-mappings: true
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
